name: Ruby Test
on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.46.0
      - name: Install dependencies
        run: bundle install
      - name: Lint
        uses: artplan1/brakeman-action@v1.2.1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.46.0
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
